name: NCC Scout Suite Monthly Scan

permissions:
  id-token: write
  contents: read
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' 

jobs:
  staging-account:
    name: Run NCC Scout for staging Account
    uses: ./.github/workflows/ncc.yml
    secrets: inherit
    with:
      environment: the5ers-staging

  root-account:
    name: Run NCC Scout for root Account
    uses: ./.github/workflows/ncc.yml
    secrets: inherit
    with:
      environment: the5ers-root

  prod-account:
    name: Run NCare C Scout for Prod Account
    uses: ./.github/workflows/ncc.yml
    secrets: inherit
    with:
      environment: the5ers-production
  
  ttp-staging-account:
    name: Run NCC Scout for ttp-staging Account
    uses: ./.github/workflows/ncc.yml
    secrets: inherit
    with:
      environment: ttp-staging

  ttp-prod-account:
    name: Run NCC Scout for ttp-prod Account
    uses: ./.github/workflows/ncc.yml
    secrets: inherit
    with:
      environment: ttp-prod
