name: NCC Scout Suite Monthly Scan

permissions:
  id-token: write
  contents: read
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight UTC on the 1st of every month

jobs:
  staging-account:
    name: Run NCC Scout for staging Account
    uses: ./.github/workflows/the5ers-ncc.yaml
    secrets: inherit
    with:
      environment: the5ers-staging

  root-account:
    name: Run NCC Scout for root Account
    uses: ./.github/workflows/the5ers-ncc.yaml
    secrets: inherit
    with:
      environment: the5ers-root

  prod-account:
    name: Run NCC Scout for Prod Account
    uses: ./.github/workflows/the5ers-ncc.yaml
    secrets: inherit
    with:
      environment: the5ers-production

  ttp-staging-account:
    name: Run NCC Scout for ttp-staging Account
    uses: ./.github/workflows/the5ers-ncc.yaml
    secrets: inherit
    with:
      environment: ttp-staging

  ttp-prod-account:
    name: Run NCC Scout for ttp-prod Account
    uses: ./.github/workflows/the5ers-ncc.yaml
    secrets: inherit
    with:
      environment: ttp-prod

  send_reports_to_root_s3:
    name: Send Consolidated Reports to S3
    needs: ["staging-account", "root-account", "prod-account", "ttp-staging-account", "ttp-prod-account"]
    uses: ./.github/workflows/report_to_s3.yaml
