name: Sync to R2

on:
  push:
    branches:
      - main  # Trigger for main branch pushes

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout R1
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'https.piyush@gmail.com'

      - name: Clone R2
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/Piyush-Fury/R2.git
          rsync -av --exclude='.git' --exclude='R2' --exclude='.github/workflows' ./ R2/

      - name: Process Files (Add Prod- Prefix)
        run: |
          cd R2
          for file in $(find . -type f); do
            if [[ $(basename $file) != Prod-* ]]; then
              mv "$file" "$(dirname $file)/Prod-$(basename $file)"
            fi
          done

      - name: Replace Image Tags
        run: |
          cd R2
          # Example: Update Docker image tags
          find . -type f -name 'Prod-*.yaml' -exec sed -i 's/image: .*:\(.*\)/image: myimage:\1/' {} \;

      - name: Push to R2
        run: |
          cd R2
          git add .
          git commit -m "Sync from R1 - Automated by GitHub Actions" || echo "No changes to commit"
          git branch -M main
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Piyush-Fury/R2.git
