name: Sync to R2

on:
  push:
    branches:
      - main  # Trigger for main branch pushes

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout R1
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name 'Piyush Agrawal'
          git config --global user.email 'https.piyush@gmail.com'

      - name: Process Files (Add Prod- Prefix)
        run: |
          for file in $(find . -type f); do
            if [[ $(basename $file) != Prod-* ]]; then
              mv "$file" "$(dirname $file)/Prod-$(basename $file)"
            fi
          done

      - name: Replace Image Tags
        run: |
          # Example: Update Docker image tags
          find . -type f -name 'Prod-*.yaml' -exec sed -i 's/image: .*:\(.*\)/image: myimage:\1/' {} \;

      - name: Debug Token and Repository Access
        run: |
          echo "Token used: ${{ secrets.PAT }}"
          git remote -v
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/Piyush-Fury/R2.git
          git remote -v

      - name: Push to R2 with PAT
        run: |
          git add .
          git commit -m "Sync from R1 - Automated by GitHub Actions" || echo "No changes to commit"
          git branch -M main
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Piyush-Fury/R2.git

      - name: Push to R2 with GITHUB_TOKEN (alternative method)
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Piyush-Fury/R2.git
