name: Sync R1 to R2 with Prod Prefix

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch (change to match your branch if necessary)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository R1
        uses: actions/checkout@v3

      - name: Set up Git for Repository R2
        run: |
          git config --global user.name "Piyush Agrawal"
          git config --global user.email "https.piyush@gmail.com"

      - name: Clone Repository R2
        run: |
          git clone https://github.com/Piyush-Fury/R2.git

      - name: Rename Files with Prod Prefix and Sync to R2
        run: |
          # For each file in the source repo (R1), rename it with Prod- prefix and sync it to R2
          for file in $GITHUB_WORKSPACE/*; do
            if [ -f "$file" ]; then
              # Get the filename without the path
              filename=$(basename "$file")
              # Prefix the filename with "Prod-"
              mv "$file" "$GITHUB_WORKSPACE/Prod-$filename"
            fi
          done

          # Sync the renamed files to R2, excluding .git and .github
          rsync -av --exclude='.git' --exclude='.github' $GITHUB_WORKSPACE/ R2/

          # Commit and push from inside the R2 repo
          cd R2
          git add .
          git commit -m "Sync changes from R1 to R2 with Prod prefix" || echo "No changes to commit"
          
          # Use the GitHub token for authentication
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Piyush-Fury/R2.git main
