name: Sync R1 to R2

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch (change to match your branch if necessary)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository R1
        uses: actions/checkout@v3

      - name: Set up Git for Repository R2
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Clone Repository R2
        run: |
          git clone https://github.com/your-username/repo2.git
          cd repo2
          git checkout main  # Ensure you're on the right branch (change if needed)

      - name: Sync Changes from R1 to R2
        run: |
          cd repo2
          # Copy the files from R1 to R2, but avoid copying the R2 directory itself
          cp -r ../* .  # This copies all files except the repo2 directory
          git add .
          git commit -m "Sync changes from R1 to R2"
          git push origin main
