name: Sync Changes to R2

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository R1
        uses: actions/checkout@v3
        
      - name: Set up Git
        uses: actions/setup-git@v2
        
      - name: Clone Repository R2
        run: git clone https://github.com/Piyush-Fury/R2.git

      - name: Sync Changes to R2 with Prefix
        run: |
          cd repo2
          git pull
          for file in $(git diff --name-only HEAD~1..HEAD); do
            if [[ -f "../$file" ]]; then
              cp "../$file" "Prod-$file"
            fi
          done
          git add .
          git commit -m "Sync changes from R1 with prefix Prod-"
          git push origin main
        
      - name: Push to Repository R2
        run: git push https://github.com/Piyush-Fury/R2.git main
