name: Send Consolidated Reports

permissions:
  id-token: write
  contents: read
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0 1 * *'  # Runs at 00:15 UTC on the 1st day of every month

jobs:
  send-reports:
    runs-on: ubuntu-latest

    environment: Download

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set DATE variable
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GH_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: ${{ secrets.GH_OIDC_ROLE_SESSION_NAME }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Activate Service Account
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud auth list
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Create reports directory
        run: mkdir reports


      - name: Download AWS reports
        run: |
          ################### this is For the5ers-production ########################
          BUCKET_NAME="the5ers-scout-suite-reports"
          PREFIX="aws/the5ers-production/"
          
          # Get the latest report path
          # AWS_REPORT_PATH=$(aws s3 ls s3://$BUCKET_NAME/$PREFIX --recursive | sort | tail -n 1 | awk '{print $4}')
          
          # Remove the prefix from the path
          # AWS_REPORT_KEY="${AWS_REPORT_PATH#aws/}"
          
          # Construct the full S3 URI
          # S3_URI="s3://$BUCKET_NAME/$AWS_REPORT_KEY"
          
          # Print the constructed S3 URI
          # echo "Latest AWS report URI: $S3_URI"

          # echo "Hello"
          
          # aws s3 cp $S3_URI reports/ --region ${{ secrets.AWS_REGION }}
          #echo "Production success"

          AWS_REPORT_PATH=$(aws s3 ls s3://$BUCKET_NAME/$PREFIX --recursive | sort | tail -n 1 | awk '{print "s3://'$BUCKET_NAME'/"$4}')
          
          echo "Downloading AWS report from: $AWS_REPORT_PATH"
          aws s3 cp "$AWS_REPORT_PATH" reports/

      - name: Download GCP reports
        run: |
          # Get the latest report from the GCP bucket
          GCP_REPORT_PATH=$(gsutil ls gs://the5ers-scout-suite-report/gcp/ttp-staging/* | sort | tail -n 1)
          gsutil cp $GCP_REPORT_PATH reports/
          
      - name: Zip the reports directory
        run: |
          zip -r scout-suite-reports-${{ env.DATE }}.zip reports

      - name: Upload zipped reports to Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: files.uploadV2
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
            initial_comment: "Scout Suite consolidated reports for all environments are ready. 📦"
            file: "scout-suite-reports-${{ env.DATE }}.zip"
            filename: "scout-suite-reports-${{ env.DATE }}.zip"
